### PR TITLE
Case insensitive username

### PR DESCRIPTION
**Pull request by uttamdhakal**
Overwritten default User model to make username case insensitive

### CODE REVIEW

**Review by henryk3dp — CHANGES_REQUESTED** [review]
you have deleted and overwritten existing migrations, which breaks the upgrade path for existing databases. please reference the wiki  https://github.com/SNDjango/server/wiki/Contributing#clean-up-your-migrations  
also, instead of creating a new user model (which might be not such a good idea) you could instead just extend the existing model. https://docs.djangoproject.com/en/1.11/topics/auth/customizing/#extending-the-existing-user-model
though i wounder if a simple transformation to lowercase at login and signup wouldn't do.

**Comment by pr0me** [comment]
I would strongly suggest a cast to lowercase on login/sign up, too. 
The hassle with the db for this simple task is not necessary.

**Comment by uttamdhakal** [comment]
We can lowercase the login/signup but we don't want to force a user to choose all lowercase username right? A user can create a mixed case username and we should save and display it as it is in his/her profile page. That was my idea. It is already implemented and works fine so there is no hassle anymore ;)

**Comment by henryk3dp** [comment]
@uttamdhakal  migrations are still broken. the [migrations already in devel](https://github.com/SNDjango/server/tree/devel/snd/image_board/migrations) are not to be touched.

**Review by ericaivarsson — COMMENTED** [review]
According to @Teszko previous comments, I´m not sure if all issues in migrations have been solved. 
What I potentially find that seems to be missing are: 


    class Migration(migrations.Migration):

     initial = True

         dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
         ]
    ; 


and inside to CreateModel (comment): 

               ('comment_text', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now=True)),
                ('author',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, 
    to=settings.AUTH_USER_MODEL)), 

and a few other things I´m not too sure of. I have checkout the branch and code seem to be working, but I Don´t want to merge this as I am not entirely sure about migrations. Please can someone else also check?

**Pull request closed without merging**
