### PR TITLE
#138 upvote downvote comment

### PR DESCRIPTION
**Pull request by tatankayotanka**
To review, pay attention to the following
1. Thumb up and thumb down button for each comment
2. Each user can upvote and dowvote each comment only once (tooltip exists on hover to remind the user of this fact)
3. Downvote/upvote count is diplayed

### CODE REVIEW

**Review by henryk3dp — COMMENTED** [review]
A few things I noticed:
console.log calls, while not important, should probably be removed after debugging. 
The up- and downvotes have no limit for one user. people can just spam, maybe it would be a good idea to track who already voted and only allow one up- or downvote. 
the way you implemented it is that you use jquery to send an ajax get request to the server and once the response arrives you display whatever arrives. in a production environment this might have a long delay. maybe it would be good to increment the counter when you press on upvote, but then overwrite it once the http response arrives to give the user rapid feedback. the like implementation for posts has the same shortcoming btw. 
otherwise it looks very nice.

**Comment by tatankayotanka** [comment]
@Teszko I will try to limit each user's votes next. I might eventually need help with what you suggested for incrementing the count. Does that mean, we just first give the appearance of a number incremented for the user to see and let the count refresh when data arrived? See the following

       $('.upvotes').click(function (e) {
                var el = $(e.target);
                var commentid = $(this).attr("data-comment-id");
                el.children("span").text(Number(el.children("span").text())+1);
                $.get('/upvote_comment/', {comment_id: commentid}, function (data) {
                    el.children("span").text(data.upvotes);
                });
            });

Does this do the job? ^^
I will clean up comments when I finish. Will let you know when I am sure about finishing this ticket for this sprint. Thanks!

**Comment by tatankayotanka** [comment]
@Teszko 
Each user can up/downvote once on each comment.
Faster user feedback through incrementing integer not included, as the limit is 1. If a use clicks on the button multiple times, he/she sees the number incrementing, while it doesn't in the backend.
Instead, tooltip over the button is implemented to remind the user he/she has only one vote

comments in script removed.

**Comment by henryk3dp** [comment]
@tatankayotanka yes, that code example you provided is how i imagined it. but it's not that important. i noticed a different problem though: [Video](https://gfycat.com/BasicDeliriousHuia)
the problem seems to be in index.html in line 134 and 143. 
if you click on the button, your code works, but if you click on the glyphicon inside the button, the code still tries to get the child element, which does not exist and the text inside the button does not get updated.

**Comment by pr0me** [comment]
In addition to that, i think it would be rational, that one user can only either up- OR downvote one comment, not both.

**Review by ericaivarsson — APPROVED** [review]
The code does what was put in acceptance criteria. I approve it, but i think we should definitely create a spike ticket for the following and fix in the next sprint: 

1) be able to "regret" ones choice. So once I have liked, i should be able to click on like button and it will now be neutral (similarly to how we can subscribe/unsubscribe) 
2) As Lukas said, the user should not be able to dislike and like at the same time. If he had first clicked on like, then when clicking on dislike, the like should be brought back to "neutral".

**Pull request merged**
