### PR TITLE
Add serializers, html endpoints for API v0.1

### PR DESCRIPTION
**Pull request by atamankina**
Adjust settings, dependencies.
Serializers (first version) for all objects. Navigable API views.

### CODE REVIEW

**Comment by henryk3dp** [comment]
You've set permissons to only allow usage by admin user. is that intentional? i would imagine regular users need access too.

**Comment by henryk3dp** [comment]
I just tested if user generated text is properly escaped, and it is, which is nice. 
injection_test

**Comment by atamankina** [comment]
@Teszko I have set the admin user permissions as default for the reason it gives access to all objects - I have specified it in the user guide.  The html endpoints also show more info than necessary and some requests will be declined - but it is the version 0.1. I am also still working on other kind of authentication.

**Comment by henryk3dp** [comment]
that's sensible.

**Review by henryk3dp — COMMENTED** [review]
works as intended.

**Review by henryk3dp — APPROVED** [review]

**Pull request merged**
