### PR TITLE
Edit user profile #48

### PR DESCRIPTION
**Pull request by uttamdhakal**

### CODE REVIEW

**Comment by henryk3dp** [comment]
Don't push your database, please.

**Comment by uttamdhakal** [comment]
After deleting the database and all the  migrations, travis test failed. 
"relation "auth_user" does not exist", it has to something with migration, I guess

**Comment by uttamdhakal** [comment]
Any Idea how can I resolve conflicts for snd/db.sqlite3. I followed command line instructions mentioned above but without any success.

**Comment by ericaivarsson** [comment]
@uttamdhakal  any idea how we can solve the conflicts of this one?

**Pull request closed without merging**
