### PR TITLE
Faq page #30

### PR DESCRIPTION
**Pull request by ericaivarsson**
Please review this #30 .

### CODE REVIEW

**Comment by pr0me** [comment]
please be sure to finalize your functionality before committing a Pull Request

**Comment by ericaivarsson** [comment]
@pr0me sorry, actually I was just following our steps on our wiki word by word without realising I was not done yet with the functionality.

**Comment by ericaivarsson** [comment]
OKIDOKI, @pr0me @Teszko @stbrand I´m finally done... hehe :)

**Comment by ericaivarsson** [comment]
regarding the conflicts in CSS - i have tried to pull but they don´t get updated. Should I simply copy the additional lines and paste into my css and commit again? Or how do I solve this issue?  

screen shot 2017-06-16 at 01 39 36

**Comment by ericaivarsson** [comment]
Ok it seems like I have managed to resolve the conflicts. I´m not sure if the issue before was that I was always just typing "git fetch" as per our wiki, but Github told me to use "git fetch origin". Has this perhaps been the reason why my css did not get updated as other people worked on the remote? I´m confused, but the conflict is solved now anyway!

**Comment by henryk3dp** [comment]
git fetch  fetches from the origin remote by default. using git fetch origin has no different effect.

**Comment by ericaivarsson** [comment]
Finally done....!

**Review by henryk3dp — CHANGES_REQUESTED** [review]
you added styling to generic html elements in a file that is globally included. this can have unwanted sideeffects. use classes instead and put them inside the style block.

please fix indentation in faq.html.  four spaces is what we use in other documents. 
you also have conflicts to resolve. reading up on how to resolve them would probably be advisable.

**Comment by henryk3dp** [comment]
PR is stale.

**Comment by ericaivarsson** [comment]
I have now fixed all issues as per the change request by @Teszko . 

I know there has been som conversation about making this page a dynamic one, however that is not stated in the acceptance critera, was never passed by the PO and was never discussed by the team, or part of the time estimation for this ticket. If we want to make this page dynamic, I would say we would have to open a improvement-ticket for that. And then we have to prioritize and see if that is of high priority or not.

**Comment by henryk3dp** [comment]
neither the indentation issue nor the styling of generic css elements in a globally imported file has been fixed. 
Also 22 commits for adding a static page is unacceptable. please read up on git squash https://www.devroom.io/2011/07/05/git-squash-your-latests-commits-into-one/
I still think it's complete bullshit to add a static page and tim can smell bullshit ten miles against the wind. 
The ticket exists like this only because you created it and it flew under the radar of other people.

**Comment by ericaivarsson** [comment]
@Teszko I apologize for the vast amount of commits, but I was just following the guidelines that commits should represent as small changes as possible, so in my understanding at the time I was doing the right thing. Now I have learnt about squash, but I believe this should have been put into our guidelines on the wiki inside how to contribute. The problem now is that those commits are already pushed, and according to several recommendations online I should now leave them where they are and not squash. I have learnt the lesson for the next time. 

Regarding the relevance of this ticket: I created it only two days into Sprint 1 and then it was resting in Product Backlog until our PO decided to put it inside sprint backlog for Sprint 2. If this item was not accepted by the team, then it should never have passed to the sprint backlog. But it did, so I assumed that it was accepted, specially since the PO pushed it to Sprint 2. 

Nevertheless, I see the problem here and I am totally on your side. I just wish it would have been raised earlier before all hours had been put into a useless page. 

Two things can help avoiding these situations in the future : Definition of Ready, and a proper Grooming before sprint planning meeting. We don´t have either of these, and not only that, we don´t even do the planning meeting properly. And this is the result. We could have been alot more efficient and not wasted my hours on this task and your hours reviewing it, if it was not supposed to have passed at all.

**Comment by ericaivarsson** [comment]
@Teszko So it seems like I misunderstood your comment about styling of generic html elements the first time you mentioned it, as I thought I was supposed to take away all styling from the .html and put into .css, nevertheless, after doing that, you mentioned again that I had not fixed the issue. I then understood it as that I should not include any styling in the main.css and have everything inside the style block inside my .html code. However your comment is still not clear enough, so I would appreciate if you would let me know if now is the way that you actually meant.

**Comment by ericaivarsson** [comment]
@Teszko Other than that, As soon as my code review has been accepted, I would suggest we merge this and push this to QA and let QA @tatankayotanka @atamankina  test if this ticket complies with the acceptance criteria. 

If we want to have a dynamic FAQ we should open a new ticket for that and then discuss whether or not we think it´s valuable enough to put into Sprint 4 or leave it like it is already. Because that discussion does not belong here at all.

**Review by henryk3dp — DISMISSED** [review]

**Comment by henryk3dp** [comment]
I would suggest to discuss this in slack. this is after all a group assignment.

**Comment by ericaivarsson** [comment]
The review from @Teszko was dismissed by himself, but this still needs one approved review if to be merged.

**Review by BenKet — APPROVED** [review]

**Pull request merged**
