### PR TITLE
Footer #142

### PR DESCRIPTION
**Pull request by BenKet**
As a user I can see a footer on each page, with some links and network icons (without funktion yet). The footer is always at the bottom (not fixed) even if the page is smaller than the screen.

In content_items.html and content_items.html were some tags not closed. Fixed it.

### CODE REVIEW

**Review by pr0me — CHANGES_REQUESTED** [review]
Deal breaker: Not responsive (at all)

Additionals notes:
* update links as far as possible, def. remove old facebook etc. third-party links.
* Featuring a small TUGag logo in the footer would be nice imho.

**Comment by BenKet** [comment]
Oh yeah, saw what you mean! Tryed to fix it, but got a outher problem. We may find a solution tomorrow together.

**Review by BenKet — COMMENTED** [review]
Fixed the responsive design :)
deleted the links

The logo were nice to add but we should think about the logo and the name

**Review by ericaivarsson — CHANGES_REQUESTED** [review]
there are a few issues: 
1) Logos for Facebook etc are way too large. (i would go with 30 or 40px instead of 100px) 
2) The whole footer is too big. Normal is 60-100px. 
On my Macbook 13inch it covers almost half of the screen (ok im exageratting now , but it´s really too large).  Now it´s 230, I would go with something like 70. I tried to do it myself but then it didnt stick to the bottom of the page, can you solve that? 
3) take down padding (I would go with 5px) 
4) Change colour to same as navbar (#404040) 
5) Change TU Gag network for " < Company Name > 
6) take off "team" and "jobs" to save space. 
7) If possible, please change the way it reacts on mobile device, it fills up the whole screen.

**Comment by ericaivarsson** [comment]
screen shot 2017-06-30 at 00 31 02
This really does not look pretty. (Macbook air, 13 inch, safari 9.1.2 ) 

screen shot 2017-06-30 at 00 33 58
It ruins the screen for the user, when doing things on the website like uploading a post. 

screen shot 2017-06-30 at 00 33 26 
How it would look on mobile device - takes way too much space.

**Comment by ericaivarsson** [comment]
I know we don´t have to go for perfectionism, but it would be really nice if the Footer could be hidden until scrolled all way down like on github. Also github has a really small footer and it doesnt drag any attention, because it´s same colour as the background. 

Another cool way of creating the footer is as per snapchats website: https://snapchat.com it´s also always hidden in every screen size until scrolled down. Then for mobile device the sections are divided into drop downs to create space. I don´t think this is necessary though, I´d go for something like the one github offers. 

screen shot 2017-06-30 at 01 19 04

**Pull request closed without merging**
